### ISSUE TITLE
Completely switch to Dependency Injection and Play 2.6

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#1622]
[edited 2018 by @fm3]

For reference: migration guides [2.4-to-2.5](https://www.playframework.com/documentation/2.6.x/Migration25) and [2.5-to-2.6](https://www.playframework.com/documentation/2.6.x/Migration26)

### Prerequisites 
- [x] sbt needs to be >= 0.13.15
- [x] scala needs to be >= 2.11

### Steps relevant to us in migrating to 2.5
→ PR #3125
- [x] in `conf/*.xml`, replace `play.api.Logger$ColoredLevel` with `play.api.libs.logback.ColoredLevel`
- [x] `Global.scala` inherits from `GlobalSettings`, [which has been removed](https://www.playframework.com/documentation/2.6.x/GlobalSettings)
- [x] CSRF/CORS filters are now stricter, we should double-check that nothing is blocked that should work
- [x] sendFile (which we use for zip) is changed [from attachment to inline
](https://www.playframework.com/documentation/2.6.x/Migration25#Changes-to-sendFile,-sendPath-and-sendResource-methods) (cf [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)). We might want to explicitly set it to attachment
- [x] [streaming APIs have changed](https://www.playframework.com/documentation/2.6.x/StreamsMigration25) , relevant parts for us include `chunked/stream/Source`, `BodyParser`/`result.body`, 
- [x] conflict with grpc-netty, need to use gprc-netty-shaded
- [x] conflict with standalone ws, need to move RPC from util to datastore (where play is dependency)
- [x] silhouette needs to be upgraded to 4.0
- [x] get log-level definitions to work in logback.xml

### Steps relevant to us in migrating from 2.5 to 2.6
→ PR #3198 
- [x] silhouette needs to be upgraded to 5.0 [and slightly adapted](https://www.silhouette.rocks/v5.0/docs/migration-guide)
- [x] Ok.chunked(stream) is no longer supported
- [x] We might have to [inject json body parsers](https://www.playframework.com/documentation/2.6.x/Migration26#Scala-Controller-changes) into controllers
- [x] Configuration accessors [have changed](https://www.playframework.com/documentation/2.6.x/Migration26#Scala-Configuration-API)
- [x] Execution Implicits [now need to be injected](play.api.libs.concurrent.Execution)
- [x] `test.FakeApplication` is [no longer supported](https://www.playframework.com/documentation/2.6.x/Migration26#Java-API), we might change the `End2EndSpec`
- [x] look up of Mime Types [has changed](play.api.libs.MimeTypes)
- [x] some config keys have changed (for us: `play.crypto.secret` becomes `play.http.secret.key`)
- [x] I18nSupport [no longer needs](https://www.playframework.com/documentation/2.6.x/MessagesMigration26#Smoother-I18nSupport) `val messagesApi: MessagesApi` but rather a `MessagesProvider` needs to be passed around from the controllers
- [x] ActionBuilders cannot take custom parameters anymore
- [ ] The [Cache API has changed](https://www.playframework.com/documentation/2.6.x/CacheMigration26) (old is still ok, just deprecated)
- [ ] Timeouts [have changed](https://www.playframework.com/documentation/2.6.x/Migration26#Akka-HTTP-server-timeouts) (due to Akka HTTP backend), we might want to overwrite them (let’s see if this comes up)
- [ ] grpc-netty should be usable again (no conflicting netty dependencies?) (can also be follow-up PR)
