### ISSUE TITLE
Use Backbone

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#165]
In the future we should use Backbone for everything in the frontend. Especially all the user / project / dataset admin stuff could easily be converted into Backbone.Marionette view.

All these changes will probably require changes in the backend as well, since the frontend and backend will solely communicate over a REST interface. Where possible we should rely on Backbone to do the REST calls. 

Some of the groundwork was already done in #153. 

TODO
- [x] Replace Routing with Backbone.Router #171 
- [x] Replace EventMixin with Backbone.Events
- [ ] ~~Use [Backbone Nested Model](http://documentup.com/afeld/backbone-nested/)~~
- [x] Upgrade to Bootstrap 3.0 #273
- [ ] ~~Use "requireable" template modules for HTML~~
- Admin Views:
  - [x] dashboard #269
  - [x] Datasets table #203 
  - [x] Users table #153
  - [x] Teams table #190 
  - [x] Projects table
  - [ ] Tasks
    - [x] Task table #195
    - [x] Task Overview Graph #171 (somewhat)
    - [x] Task Algorithm #171 (somewhat)
    - [ ] Task Types #290 
    - [ ] Task Creation 
### Tracing View
- [x] Layout view for all containers #165
- Left Menu
  - [x] save / finish button #165  
  - [x] position / rotation  #165
  - [x] settings for activeNode, activeTree etc
  - [x] dataset info view #165
  - [x] user settings view #271  (now #165)
    - [x] make headers clickable (not just a-Tag)
    - [x] add open / close icons 
  - [x] volumne mode controls view
  - [x] tracing mode selection view #165
    - [x] set active button on startup
- Right Menu
  - [x] tree viewer #165
  - [x] trees manager viewer
    - [x] display trees / update on changes
    - [x] new / delete buttons
    - [x] sorting
    - [x] set Tree active on click
    - [x] scroll to newly created tree
  - [ ] comments view
    - [x] new comment
    - [x] previous / next comment
    - [x] delete comment
    - [x] set active node on comment change
    - [x] center active node on comment change
    - [x] delete comment on node deletion
    - [x] delete comment on tree deletion
    - [x] save something on comment deletion??? 
    - [x] scroll to newly created comment
    - [ ] show tree name before comments
      - [ ] possibly make comments part of the node / tree ???  
- Tracing View
  - [x] wrap as backbone.view #165 
  - [ ] ~~move resizing code~~
  - [ ] ~~move 3D buttons code~~
  - [x] remove play template #165
  - [x] check template's "access not allowed" message 
### Models
- [ ] ~~make Model.coffee a DeepModel~~
### Public Tracing View
- [x] load same template as normal tracing #165
- [x] alpha slider??? #165
- [x] credits / logos view #165

CHECKLIST
- [x] Is the enhancements.coffee dead?
- [x] Is pagination part of a PaginationView? #194
- [x] Is Oxalis free of "data-ajax"?

OTHER TASKS
- [ ] talk about tlt.coffee. Why coffeescript and not compiled js?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/165/create?referer=github" target="_blank">Log Time</a>
