### ISSUE TITLE
Reduxify SkeletonTracings

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#1709]
### Todos
- [x] Fix Abstract Tree Renderer
- [x] Add sagas for saving (@norman)
- [x] Fix Finish / Archive Tracing
- [x] Fix comment list
- [x] Fix node size
- [x] Correctly initialize tracing from server (@norman)
- [x] reducer for splitting trees after node deletion (@philipp)
- [x] correctly center camera after certain actions
- [x] ~~fix branchvideomode?~~
- [x] fix flow errors
- [x] fix `activeTreeId == null` (flow errors)
- [x] fix linting errors 
- [x] delete old files
- [x] new node animation @hotzenklotz 
- [x] tree invisibility keyboard shortcut ("1")
- [x] render more than one tree
- [x] everything with tree merging
- [x] new tree names
- [x] [Warning when leaving the page and state is not saved yet](https://github.com/scalableminds/webknossos/pull/1710/files#diff-54cfa75aeef119ca105706d52b4afd15R88)
- [x] put Flycam2d/3d in store @normanrz 
- [x] fix API @philippotto 
- [x] fix VolumeTracing
- [x] add `shouldComponentUpdate` to all settings input views @hotzenklotz 
- [x] fix zoom slider @normanrz
- [x] merging trees (shift + alt click) brakes saving @normanrz 
- [x] deleting trees brakes saving @normanrz 
- [x] use scaleinfo2 @normanrz
 
### Heiko's Testing Round 1
- [x] no zoom in to 1 pixel possible (we use that to check the voxel size sometimes)
- [x] clicked dashboard but do not got there
- [x] deleted all trees but still have remaining nodes
- [x] are all edges white now??? Compare 9:15 in 3D mode no edges visible
- [x] clicked 100 times "j" but did not jumped to  a branchpoint
- [x] in flight mode I do not jump to that BP when clicked "j" but node seems to be activated

### Heiko's Testing Round 2
- [x] Action Bar font very thin, not really good to read
- [x] I deleted the node but only the color changed  and  I was no longer able to shift-leftclick that node
- [x] window freeze, can't move, click in viewports, had to reload (1:50)
- [x] could not activate that top left node (2:50)
- [x] in flight set branchpoints have the same color as the tree
- [x] in flight if no remaining branchpoint and "j" clicked I jump to the active node instead of just show "no more branchpoints"
- [x] viewport options: I think 2 digits after comma is more than enough
And the number 1.26456547456 should give the exact same result like 1.26745764654 or 1.26
(to be able to create exact same conditions even with only 2 digits after comma)
- [x] interesting, I can increase particle size for all nodes with a high value but only for the active node with small values. Is this a feature for any reason? 8a0050c
- [x] show resolution in dataset info
- [x] no difference between medium and high quality 

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1709/create?referer=github" target="_blank">Log Time</a>
