### ISSUE TITLE
Remove mongo residue

### ISSUE THREAD

**Issue by fm3** [scalableminds/webknossos#2447]
We still have the play mongo module activated, and we have a lot of (now dead) mongo util code.
The one thing we will for now keep is the BSONObjectId.

I suggest doing this in a number of small PRs to make merging easier. Not everything has to be done immediately.

- [x] remove mongo-related scala code that is already not referenced anymore → #2643
- [x] disable the play-mongo module in application.conf, see if anything breaks → #2657
- [x] remove mongo stuff from docker-compose / CI files → #2550
- [x] remove mongo evolutions, rename evolutions-postgres dir → #2643
- [x] remove mongo tools (like drop_db scripts etc), test db jsons → #2657
- [x] move access definition helpers etc out of `reactivemongo` package, check which parts are still used → #2872
- [x] get rid of BSONObjectId everywhere, *except* in ObjectId.generate and ObjectId.parse → related issue #2521, now finalized by PR #2958
- [x] remove mongo stuff from Dependencies.scala _(blocked by json formats with BsonID)_ → #2958
- [x] remove mongo deployments from kube? ~~(blocked by not all servers being migrated to pg yet)~~ → https://github.com/scalableminds/kube/pull/183

**Comment by jstriebel** [comment]
@fm3 for all docker/development related files in this repo it is done. I added scalableminds/docker-sbt-node-mongo#15 do remove it from the docker image also.

**Comment by fm3** [comment]
Closed by all of the above 🎉
