### ISSUE TITLE
Refactor frontend model

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2601]
The frontend model code has turned into a beast over time and it's time for some refactoring.
Module names should be made clearer, big files that do many different things should be split up, the actual initialization should be made easier to follow and understand, state should be moved into the store where appropriate.
This includes, among others, the files: `model.js, binary.js, layer.js, ndstore_layer.js, wk_layer.js`.
The improved model structure envisioned by @philippotto and me could be summarized in a couple of sentences:
Webknossos is initialized and displays a dataset that consists of several data layers (grayscale, color, segmentation data). Each layer consists of meta information (in the store), the actual data (data_cube), and pulls, resp. optionally pushes data (pull/pushqueue) to a server backend using the appropriate store adapter (wkstore/ndstore_adapter). A saga listens to position/zoomstep changes of the user and triggers the pulling of the needed data per layer.

List of tasks (create small PRs, solving one or max. two issues at a time):

- refactor wk/ndstore layers:
  - [x] layer/wk_layer/ndstore_layer should be stateless and layer state should be at one place in the store **[daniel] #2611**
    - remove ndstore
    - rename to wkstore_adapter/

- refactor binary.js
  - [x] mapping code should be moved to mappings module **[daniel] #2602**
  - [x] ping should be moved to saga that listens to position changes (views no longer need to trigger ping after rendering) **[daniel] #2687**
  - [X] GPU code should be moved to extra module **[philipp] #2764**
  - [x] binary becomes layer (or data_layer) - the layer holds references to the data_cube, pullqueue, pushqueue, etc. **[daniel] #2681**

- various:
  - [-] refactor the `fallbackLayer`, the server should ideally send the correct layers to be used - _We discussed this and it is not really possible. This stems from the fact that segmentations are a weird mix of dataset layers (existing segmentation) and volume tracings (new segmentations)._
  - [X] put resolutions into the store (superset of all layer resolutions + upsampled resolution) **[philipp] #2751**
    - per layer only the number of available resolutions needs to be saved

- refactor initialization:
  - [X] initialization code should be put into a separate module (fixes #2452) **#2760**
     - high level model initialization should be easily readable in one function or one saga (without many if/else)
  - [ ] there should be one module that "holds" the binaries (new: layers), could be called Dataset
