### ISSUE TITLE
Redesign Dataset Gallery

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2606]
Make the dataset gallery more visually pleasing. For example, the description text is often too dominant.

- [x] define main goals of redesign
- [x] mock up new design
- [x] discuss design with lab
- [x] implement design

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2606/create?referer=github" target="_blank">Log Time</a>
<a href="https://github.com/scalableminds/webknossos/issues/2771" traget="_blank"> layout changing issue</a>

**Comment by daniel-wer** [comment]
@normanrz You mentioned that you have some ideas in this regard, could you add them to this issue? :)

**Comment by normanrz** [comment]
This is what I was thinking of:

![2018-05-30 14-52](https://user-images.githubusercontent.com/335438/40721288-585920a8-6419-11e8-8a39-744c4881be37.jpg)

The multi-dataset tile would require some backend changes aswell (e.g. a dataset-group attribute)

**Comment by daniel-wer** [comment]
The dataset preview images are blurry right now as they have a size of 200x200 pixels but are displayed with a size of 400x400 pixels.
Ideally the backend should generate the preview images in a size that is closer to the display size.
Could we do this as part of the PR for this issue, @fm3? (I would wait until the PR is open and we know what size would fit best)

**Comment by fm3** [comment]
absolutely, that should [be a simple change](https://github.com/scalableminds/webknossos/blob/master/app/controllers/DataSetController.scala#L30)

**Comment by normanrz** [comment]
would it be possible to give a dynamic preview size, e.g. `.../thumbnail?size=400x400`?

**Comment by daniel-wer** [comment]
@MichaelBuessemeyer Actually, I don't think the thumbnail size needs to be configurable by the user, I would argue that this introduces unnecessary complexity.

**Comment by philippotto** [comment]
> absolutely, that should be a simple change

Since this would be an easy-win, I'd suggest to commit the one-liner which changes that to 400x400 (independent of this issue). The front-end scales the images anyway and downscaling is better than upscaling.

Norman's suggestion would be even more flexible, of course.
