### ISSUE TITLE
Improve tracing view page load performance

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#2639]
The tracing view takes quite a while to load, especially for larger tracings. There is a lot of optimization potential. This issue serves as an umbrella issue to track the page load improvement progress and list optimization ideas.

Loading timeline (using annotation 52004ce75fd6454500a7d021 with 680707 nodes as an example):
Overall time to interactive is ~30s.
  - Initial requests (dataset, info): 0.5s
  - Waiting for server (tracing request): 8.74s
  - Download tracing (12.7MB): 5s
  - Javascript intialization code (no requests, threejs object creation, texture init): 12s
  - Data loading: 4s

Optimization ideas:
  - [x] Send protoBuf objects to client instead of json-ified tracing **[daniel] #2650**
  - [x] The shaders take very long to compile (at least under Linux). It may be worthwhile to "template out" unused code to reduce shader complexity and increase compilation speed **[daniel] #2709** - _We ended up unifying the shader for the different viewports, so it only needs to be compiled once_
  - [ ] On demand tree loading (very complex - last resort) #2605

Investigated, but probably not worth it:
  - Optimize frontend initialization code
    - `skeleton.js` `createTree` takes 24% of the scripting time
    - `edge_collection.js` `loadFromArray` takes 12.5% of the scripting time
    - _Could not identify optimization potential in these functions_
  - Use DevTools Performance Audit recommendations (reduce render-blocking scripts, reduce render-blocking stylesheets, minify css, unused css rules)
    - _CSS files are too small, optimization wouldn't have a big impact_
    - _CSS files could be split up into different files for different media types to avoid render-blocking (https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css). I didn't find a way to do this automatically_
  - The actual data is only loaded after the tracing has been downloaded and everything else was initialized. In theory it should be possible to start downloading data much earlier, for example, while waiting for the server to prepare the tracing.
    - _We would need editPosition/editRotation/zoomLevel which is, for now at least, only included in the tracing response_
    - _The waiting time for the server has decreased with #2650_
    - _Refactoring would be needed, some of the code expects a tracing to be there from the beginning or never_

**Comment by philippotto** [comment]
Nice summary!

> The actual data is only loaded after the tracing has been downloaded and everything else was initialized. In theory it should be possible to start downloading data much earlier, for example, while waiting for the server to prepare the tracing. - We would need editPosition/editRotation/zoomLevel for that which is included in the tracing response

That's probably something we should do after the initialization code was refactored.

**Comment by daniel-wer** [comment]
I've updated the issue description with an evaluation and some observations of some of the optimization ideas.

**Comment by daniel-wer** [comment]
We agreed to close this issue for now, the on-demand tree loading will be tracked using its own issue #2605.
