### ISSUE TITLE
Oxalis UI annoyances

### ISSUE THREAD

**Issue by hotzenklotz** [scalableminds/webknossos#270]
### Dashboard:
- [x] Long loading time for dashboard (5s) optimize DB query! #269
- [x] scrollbar y direction for exploretive tracings
- [x] Volume / Skeleton selector is ugly #269 
### Tracing View:
- [x] "dataset" name sometimes too long. Why do we need the 'dataset' label?
- [x] split settings into tabs for user / tracing / dataset-user #165
- [x] Consider adding resizing slider / handler between left/right menus and tracing views.
- [x] Add more buttons for some keyboard shortcuts
- [x] Add real help page that explains tracing.
- [x] Replace 'tracing' / 'watching' canvas in arbitrary mode with HTML
- [x] Treeview should use full available width #165
- [x] in 3D view: make planes double-sided
- [x] in 'trees' tab: always show text input field #273 
- [x] in 'trees' tab: change color button is not discoverable
- [x] in 'trees' tab: sort by button is ugly and has wrong icon #273 
- [x] in 'comments' tab: bullet points are weird
- [x] in 'comments' tab: break long words #273 
- [x] in volume mode: zooming in/out causes texture artefacts
### General:
- [x] reset password view is missing . Maybe under username in navbar.
- [x] save user settings as objects #165

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/270/create?referer=github" target="_blank">Log Time</a>
