### ISSUE TITLE
Rework Merge Tracing

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#2919]
The merge modal works by creating a new explorative annotation in the account of the user. The currently open tracing is not changed. From a usability aspect, it would be better if the merge would be "live" in the current tracing.

- [X] For the **"merge NML"** functionality, this is already possible via the the "upload NML" feature. We should combine these two features (e.g, remove the nml-part from the merge modal).
- [X] According to Heiko, merging a **task type** is rarely done as this would involve way too many tracings, anyway. So, we can remove it.
- [x] For merging a **project** or **explorative**, it would be also useful to have the merging in-place. We would need to investigate, whether this is feasible with regard to resources (all tracings would need to be downloaded, merged, diffed, and then the update actions would be re-uploaded and applied). Alternatively, we could also have the server conduct the merge and force a page-refresh, maybe?
