### ISSUE TITLE
Make hybrid tracings the default

### ISSUE THREAD

**Issue by daniel-wer** [scalableminds/webknossos#3433]
Followup from #3288.
At some later point we should:
- [x] remove the "Create Skeleton/Volume Tracing" links and rename the "Create Hybrid Tracing" link to "Create Tracing" (or make hybrid tracings the default)
- [x] introduce restrictions to allow/disallow skeleton or volume tracing (for tasks) #4747

**Comment by philippotto** [comment]
- [ ] ensure that the user can decide between "with" and "without" fallback layer

**Comment by normanrz** [comment]
- [ ] enable isosurface rendering in hybrid tracings (also see #3681)

**Comment by fm3** [comment]
Another issue here is that of mergeability. Skeleton-only annotations in collections (such as projects) can be merged into a compound view, while this is not defined for volumes. Compare discussion here: https://discuss.webknossos.org/t/handling-of-volume-tracing-projects-with-many-tasks/1500/4

**Comment by fm3** [comment]
[ ] remove the “use existing segmentation” dropdown menu (default to yes, add the option to remove it later)

**Comment by philippotto** [comment]
- [ ] take care that "create annotation" still works for datasets with uint64 segmentations (right now, wk defaults to creating a fallback segmentation which fails). also see: https://github.com/scalableminds/webknossos/issues/4852

**Comment by fm3** [comment]
If we still want to give the user full control there are quite a few options. Will probably look something like this, what do you think?
![image](https://user-images.githubusercontent.com/1390035/95355893-5b1b6180-08c6-11eb-92e3-703cc882c24b.png) 
or
![image](https://user-images.githubusercontent.com/1390035/95356711-3ecbf480-08c7-11eb-9369-1bcebe5232ca.png)

I’m not sure how to call the options… some of them will probably be disabled for some datasets (e.g. if there is no segmentation layer or if it is 64 bit)

**Comment by philippotto** [comment]
@fm3 Thank you for the mock-ups & the inspiration! I went with a cascading menu and only put the "create annotation" items in the menu. Let me know in case you have objections :) PR: https://github.com/scalableminds/webknossos/pull/4939
