### ISSUE TITLE
Better Feature Analytics

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos#3459]
We're not using analytics in a meaningful way yet. Would be great if we can get a better insight into what features people actually use and how frequently.

- [ ] Make a list of features that we want to track
- [ ] Track per organization (with event param or sth)
- [ ] Implement tracking

## List of Features (tbd)
- [ ] NML drag&drop
- [ ] Create (Skeleton,Volume,Hybrid)-Tracing
- [ ] Soma-clicking
- [ ] Dataset Import
- [ ] Tagging Annotations
- [ ] Viewing all annotations of a project

**Comment by normanrz** [comment]
@philippotto @daniel-wer @hotzenklotz Could you help me add trackable features to the list?
