### ISSUE TITLE
Finalize first iteration of magic wand

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#3960]
- [ ] use newest compatible model
- [x] finalize UI / workflow
- [x] optimize performance (shrink bounding box and extend automatically)
