### ISSUE TITLE
Improve wK Core UI / Layout

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5028]
- [x] Show "resource" summary of tracing in info tab #4836
- [x] Rework Ortho Viewport Layouting #5307
- [x] Iterate on (skeleton) toolbar #4997
- [x] Re-think keyboard and mouse shortcuts #4972
- [x] Reorganize content of panels in core UI #5231
- [x] Brainstorm on wK layout #4996
- [x] Add more information to the info tab #4918
- [x] Add status bar to show important information #4995
- [x] Rework core layout (using sidebars) #5230
- [x] Add context menu for nodes #4950

(Converted from ZenHub)

**Comment by hotzenklotz** [comment]
[ ] Show "resource" summary of tracing in info tab #4836
[ ] Rework Ortho Viewport Layouting #5307
[ ] Iterate on (skeleton) toolbar #4997
[ ] Re-think keyboard and mouse shortcuts #4972
[ ] Reorganize content of panels in core UI #5231
[ ] Brainstorm on wK layout #4996
[ ] Add more information to the info tab #4918
[ ] Add status bar to show important information #4995
[ ] Rework core layout (using sidebars) #5230
[ ] Add context menu for nodes #4950

(Converted from ZenHub)

**Comment by hotzenklotz** [comment]
Closing, since all to dos have been ticked.
