### ISSUE TITLE
Implement Metrics tracking

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5134]
I would like to implement the tracking of events for analytics on the backend. Events consist typically of
- an event type (e.g. `signup`, `open_annotation`, `upload_dataset`, `invite_colleague`),
- a user identifier (e.g. email address or multiuser database id),
- some event properties (e.g. dataset name, annotation id),
- some user properties (e.g. organization) and,
- a timestamp.

These events are sent to an HTTP API of the analytics provider. I think it would be great to have an abstraction for that, so that we could switch to a different provider in the future. All dashboards and metrics are then derived from the stream of events in the analytics tool.

Events to track (initially):

wk internal:
- [x] Signup (+ source of signup: invite vs frontpage)
- [x] Invite colleagues
- [x] Join organization
- [x] Open Dataset
- [x] Create Annotation
- [x] Open Annotation (+ owner of annotation)
- [x] Trigger long-running job
- [x] Download Annotations

triggered from datastore:
- [x] Upload Dataset (+ dataset name, size, type?)
- [x] Change Dataset Settings
- [x] Trigger Isosurface rendering

triggered from tracingstore
- [x] Save Annotation (maybe per update action)

API definition for sending the events: https://developers.amplitude.com/docs/http-api-v2
Example:
```bash
curl --data '{"api_key": "...", "events": [{"user_id": "john_doe@gmail.com", "event_type": "watch_tutorial",
  "user_properties": {"Cohort": "Test A"}}]}' https://api.amplitude.com/2/httpapi
```

Maybe we'll add some frontend tracking in the future as well (e.g. open share modal, select brush tool etc).

**Comment by normanrz** [comment]
We should also include a property to distinguish the instance (maybe the `http.uri` from conf)
