### ISSUE TITLE
Better analytics

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5135]
In order to track user growth, we should implement more analytics.

**Comment by hotzenklotz** [comment]
I am not sure if we lost the sub-issues for the epic when switching to GitHub projects? If not, are the sub-issues related to this? Or general ToDos that we can track as a check list?

**Comment by hotzenklotz** [comment]
- [x] Session IDs for analytics #5280
- [x] Track users before signup #5281
- [x] Use frontend analytics to track interesting events #5296
- [x] Frontend analytics #5348
- [x] Expose analytics endpoint for frontend #5166
- [x] Define Metrics to track #5132
- [x] Pick an Analytics tool (e.g. Mixpanel, Amplitude) #5133
- [x] Implement Metrics tracking #5134
- [x] Update user.lastActivity when tracing or uploading dataset #5082

(Converted from Zenhub)
