### ISSUE TITLE
Build job for nuclei inferral

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5555]
## Detailed Description
The existing wk job infrastructure should be used to generate a nuclei segmentation of an input (color) layer. The inferral should use a pretrained model using voxelytics. This feature can be tackled quite similarly to the existing mesh-job (which also uses the wk job infrastructure and also makes use of voxelytics).
Contact @georgwiese for insights about which model (or vx workflow) should be used for this.

## Context
The goal of this issue is to provide a generic inferral solution to users for the specific use case of detecting nuclei.

## Todos
- [x] build task in webknossos-worker
- [ ] back-end glue code for the new job type
- [ ] build rudimentary UI for this feature
  - somewhere in the UI, there should be a button to kick off this nuclei inferral (could be in the dashboard, but could also be in the core dataset view; could be both) → moved to follow-up issue #5631
