### ISSUE TITLE
Update React to v18

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5795]
The profiling dev tools in chrome stopped working for me. Probably, a good incentive to update react and reduce the technical debt a bit.

- [React 18 Upgrade Guide](https://react.dev/blog/2022/03/08/react-18-upgrade-guide)

## ToDos
- [ ] ~~Fix `enzyme` component testing environment. Enzyme is not officially compatible with React 18~~
  - Idea 1: Maybe simple online fix?: https://www.npmjs.com/package/@cfaester/enzyme-adapter-react-18
  - Idea 2: Refactor tests in `react-testing-framework`. Maybe use copliot for that? https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/
 - [x] Replace `ReactDOM.render` with `createRoot`
 - [x] Update dependencies as needed
   - [x] `antd` >=5.17.4
   - [x] `redux`
   - [x] `react-router`
   - [x] and many others. See PR for full list

**Comment by hotzenklotz** [comment]
For reference :
- [React 17 Version Summary](https://reactjs.org/blog/2020/10/20/react-v17.html)
- [React 18 Version Summary](https://reactjs.org/blog/2022/03/29/react-v18.html)
