### ISSUE TITLE
Refactor/harden volume annotation architecture/code

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#5973]
## Motivation
wK's volume annotation feature bears a lot of complexity due to the combination of the following aspects:
- dealing with potentially not-yet downloaded data (this is relevant for pure labeling but also for all other actions, such as undo)
- automatic down-/upsampling of volume data into other magnifications
- supporting front-end based undo/redo (using async compression)
- in-background, throttled persistence to server (note that versions on server are mostly not identical to versions in undo/redo stack)

The current code which backs these features is not straightforward to grasp. https://github.com/scalableminds/webknossos/pull/5955 fixes several bugs (mostly race conditions), but I'm sure we could improve the architecture + code so that we can be more confident that the volume annotation feature is robust.

## Todos
- [ ] Visualize current high-level architecture for the above features. We should clarify responsibilities of components, (time) dependencies of async operations (including the actual UI actions initiated by the user), (implicit) state machines, and potential problems in general
- [ ] Brainstorm how we could simplify the current architecture. For example:
  - [ ] lots of bucket-related code could also happen in sagas
  - [ ] more explicit state machines
  - [ ] ...
- [ ] Implement/refactor architecture
- [ ] Think about more edge cases
  - [ ] e.g., very slow save operations which might interfere with undo operations which were scheduled so early that they assume they get an older version from the backend (but in the meantime, a new version might have been stored)
- [ ] Write tests for these (the front-end test would probably need a mocked key-value store for the bucket persistence)

**Comment by MichaelBuessemeyer** [comment]
Maybe using the [command pattern](https://en.wikipedia.org/wiki/Command_pattern) might make the code more readable. [This](https://betterprogramming.pub/utilizing-the-command-pattern-to-support-undo-redo-and-history-of-operations-b28fa9d58910) looks like a kinda useful code example.
