### ISSUE TITLE
Implement Pricing Concept

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#6509]
- [x] Organization Page should be given some love. The page should also show what the possible pricing plans are and how to upgrade. @hotzenklotz 
- [x] Enforce user limit: Disable accepting invites when full
- [x] New organization fields
   - [x] paidUntil
   - [x] included users, storage
   - [x] Plans: Free, Team, Power, Team-Trial, Power-Trial, Custom
----------------------
- [x] If a feature is not supported by a pricing plan, the UI should forbid the corresponding action and tell the user how to upgrade.
   - [x] Admin pages: tasks, projects, teams, tasks tab in dashboard #6767
   - [x] Sharing modal: team sharing  #6776
   - [x] Dataset settings: allowed teams  #6776
   - [x] Pre-computed meshes: context menu, sidebar #6776
   - [x] Segmentation proof-reading button #6776
   - [x] New dataset dashboard: folder view on the left, metadata, tags, permissions #6767
- [ ] Enforce storage limit
   - [x] Maintain current storage usage
   - [ ] Disable uploading when full (also in libs) #6808 
- [ ] #6855

Also see:
- https://www.notion.so/scalableminds/webKnossos-Monetization-236159a5b7c8487a8d09945aba9f00dc
- https://docs.google.com/spreadsheets/d/1eD3UeAZd6LhlhazUlUcLLGQMptrIgOivxtq4N6lRQIg/edit#gid=0

**Comment by normanrz** [comment]
Mockup for organization page:

![organization mockup](https://user-images.githubusercontent.com/335438/195882581-e56bc8eb-5ef1-47b2-8ab8-ea027dfa26d0.png)

**Comment by Albane-dlv** [comment]
Brainstorm wording and design for unsupported features in notion page: https://www.notion.so/scalableminds/Advertise-pricing-3386806f8cc84e689bf98e2c60526f10
