### ISSUE TITLE
Paper review todo list

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#707]
This is meant to be an exhaustive list of the issues that need to be resolved for the paper review:
- [x] deployment to servers #691
- [ ] Dokumentation for oxalis deployment #692
- [x] Sphere mode view reconstruction #689
- [x] Remove merge button from the 3View screen #693
- [ ] Dataset creation using HTML form #610
- [x] Volume mode improvements for review #694
- [x] Links in help menu should open new window #695
- [x] Add big button to toggle view/trace in sphere/orthogonal #696
- [x] Make help menu for sphere and orthogonal context aware #697
- [x] Add menu point to inject JS into front end #698
- [x] Buttons for branchpoint push/pop #699
- [x] Remove Teams for paper review #700, REVERTED, DNF
- [ ] FAQ for paper review #701
- [x] Remove "create task from explorative tracing" #702
- [x] Branding of view mode #703
- [x] Segments option in view mode only when segmentation exists #704
- [x] The tutorials link in the help section is broken
- [x] Improve order of settings in view mode #706
- [x] Remove password change #716 
- [x] Fix greeting message of register user #717

Findings from further UX testing #715:
- [x] #709 Mac friendly help
- [x] #710 Zoom slider in view mode
- [x] #711 Reshuffle help in view mode
- [x] #712 Big Button for Add Node
- [x] #713 Full screen goes to black
- [x] #714 Remove FPS counter

New things Tuesday morning
- [x] #718 Remove dark theme
- [x] #719 Remove inappropiate contents
- [x] #720 Allow more browsers
- [x] #721 Multiple windows of same tracing break wK
- [x] #722 Right click open new tab....
- [x] #723 Polish interface for volume mode
- [x] #724 On Mac zoom-out in overview...
- [x] #725 Be advised on login should be removed
- [x] #727 Create new cell button
- [x] #728 Warn when trying to annotate with opacity smaller 10
- [x] #311 Create overview
- [ ] #732 License
- [x] #734 Password limit
- [x] #735 E-mail notification
- [x] #736 Remove increase experience

Wednesday
- [x] #737 Public viewing mode consistent
- [x] #738 Reviewer role
- [x] #741 Create review config
- [x] #750 Advance dataset view
- [x] #751 Interface freeze
- [x] #759 Branchpoint mode is not being honored
- [x] #761 edit Task Type
- [ ] #766 Arbitrary not being honored
- [ ] #767 Multiple datasets
- [ ] #631 Brightness to NaN
- [ ] #797 annotation not found
- [ ] #790 Teams small issues
- [ ] #798 Time can't be zero
- [x] #800 No diameter
- [ ] #36 nml download and changes in readonly
- [x] #785 Add task button bigger
- [x] #540 Tracing names to long
- [ ] #803 no task id in fn
- [ ] #805 Dataset issues

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/707/create?referer=github" target="_blank">Log Time</a>
