### ISSUE TITLE
Findings from further UX testing

### ISSUE THREAD

**Issue by boergens** [scalableminds/webknossos#715]
- [x] #709 Mac friendly help
- [ ] #710 Zoom slider in view mode
- [ ] #711 Reshuffle help in view mode
- [ ] #712 Big Button for Add Node
- [ ] #713 Full screen goes to black
- [x] #714 Remove FPS counter

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/715/create?referer=github" target="_blank">Log Time</a>
