### ISSUE TITLE
Allow to rotate viewports individually

### ISSUE THREAD

**Issue by philippotto** [scalableminds/webknossos#7569]
## Detailed Description
The orthogonal mode always renders the planes axis-oriented at the moment. In the arbitrary mode, the user can rotate the viewport, but there is only one. The user should be able to rotate the viewports in the default "ortho" view (could need some renaming then).

## Todo
- [ ] adapt bucket picking (reuse picker for arbitrary mode)
- [ ] adapt shader
- [ ] adapt mouse interactions
  - [ ] mapping of mouse position to voxel position
  - [ ] ...
- [ ] disable or support rendering of segmentation data in rotated viewport (how to interpolate?)
- [ ] disable or support volume tools

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

**Comment by normanrz** [comment]
I don't think the viewports should be rotateable individually but rather always stay orthogonal to each other.

**Comment by philippotto** [comment]
Great, then we can keep the name "orthogonal" mode for now.
