### ISSUE TITLE
Improve frontend error message handling

### ISSUE THREAD

**Issue by tmbo** [scalableminds/webknossos#911]
There are some issues with the handling of error responses from the server at different places. We need to make sure the frontend always keeps the user informed about errors and updates the displayed information accordingly. 

This relates and should solve the following issues:
- [x] User admin page doesn't show error messages on failed team administration #617
- [x] error message when finished #904
- [x] checking tracings with annyoing error message #901
- [x] Failed user experience update still leads to frontend view update #891
- [x] Show error message if assigning new experiences fails #746
- [x] bug when show all tracings of projects #907

The issues might not only need an error message fix, but showing the user that something went wrong is a first step.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/911/create?referer=github" target="_blank">Log Time</a>
